INSERT INTO SITB_SenEst1 VALUES ('Solar radiation', 'A0_Solar_radiation_avg', 'W/m2', '0', '0_X_X_600_avg');
INSERT INTO SITB_SenEst1 VALUES ('Solar Panel', 'A1_Solar_Panel_last', 'mV', '0', '4_X_X_30_last');
INSERT INTO SITB_SenEst1 VALUES ('Precipitation', 'A2_Precipitation_sum', 'mm', '1', '5_X_X_6_sum');
INSERT INTO SITB_SenEst1 VALUES ('Wind speed', 'A3_Wind_speed_avg', 'm/s', '1', '6_X_X_5_avg');
INSERT INTO SITB_SenEst1 VALUES ('Wind speed', 'A3_Wind_speed_max', 'm/s', '1', '6_X_X_5_max');
INSERT INTO SITB_SenEst1 VALUES ('Battery', 'A4_Battery_last', 'mV', '0', '7_X_X_7_last');
INSERT INTO SITB_SenEst1 VALUES ('HC Serial Number', 'A5_HC_Serial_Number_last', '0', '0', '17_X_X_508_last');
INSERT INTO SITB_SenEst1 VALUES ('HC Air temperature', 'A6_HC_Air_temperature_avg', '°C', '2', '18_X_X_506_avg');
INSERT INTO SITB_SenEst1 VALUES ('HC Air temperature', 'A6_HC_Air_temperature_max', '°C', '2', '18_X_X_506_max');
INSERT INTO SITB_SenEst1 VALUES ('HC Air temperature', 'A6_HC_Air_temperature_min', '°C', '2', '18_X_X_506_min');
INSERT INTO SITB_SenEst1 VALUES ('HC Relative humidity', 'A7_HC_Relative_humidity_avg', '%', '2', '19_X_X_507_avg');
INSERT INTO SITB_SenEst1 VALUES ('HC Relative humidity', 'A7_HC_Relative_humidity_max', '%', '2', '19_X_X_507_max');
INSERT INTO SITB_SenEst1 VALUES ('HC Relative humidity', 'A7_HC_Relative_humidity_min', '%', '2', '19_X_X_507_min');
INSERT INTO SITB_SenEst1 VALUES ('Dew Point', 'A8_Dew_Point_avg', '°C', '1', '20_X_X_21_avg');
INSERT INTO SITB_SenEst1 VALUES ('Dew Point', 'A8_Dew_Point_min', '°C', '1', '20_X_X_21_min');
INSERT INTO SITB_SenEst1 VALUES ('VPD', 'A9_VPD_avg', 'mbar', '2', '26_X_X_25_avg');
INSERT INTO SITB_SenEst1 VALUES ('VPD', 'A9_VPD_min', 'mbar', '2', '26_X_X_25_min');
INSERT INTO SITB_SenEst1 VALUES ('Wind speed max', 'A10_Wind_speed_max_max', 'm/s', '1', '31_X_X_49_max');
INSERT INTO SITB_SenEst1 VALUES ('DeltaT', 'A11_DeltaT_avg', '°C', '2', '35_X_X_27_avg');
INSERT INTO SITB_SenEst1 VALUES ('DeltaT', 'A11_DeltaT_max', '°C', '2', '35_X_X_27_max');
INSERT INTO SITB_SenEst1 VALUES ('DeltaT', 'A11_DeltaT_min', '°C', '2', '35_X_X_27_min');
INSERT INTO SITB_SenEst1 VALUES ('Watermark', 'A12_Watermark_avg', 'cbar', '0', '10004_X_X_17921_avg');
INSERT INTO SITB_SenEst1 VALUES ('5TE Battery voltage', 'A13_5TE_Battery_voltage_last', 'mV', '0', '10007_X_X_30741_last');
INSERT INTO SITB_SenEst1 VALUES ('Echo probe 10 cm', 'A14_Echo_probe_10_cm_avg', '%', '1', '10008_X_X_24067_avg');
INSERT INTO SITB_SenEst1 VALUES ('Echo probe 10 cm', 'A15_Echo_probe_10_cm_avg', '%', '1', '10009_X_X_24067_avg');
INSERT INTO SITB_SenEst1 VALUES ('Latitude', 'A16_Latitude_last', 'm', '6', '21_X_X_650_last');
INSERT INTO SITB_SenEst1 VALUES ('Longitude', 'A17_Longitude_last', 'm', '6', '22_X_X_651_last');
INSERT INTO SITB_SenEst1 VALUES ('Altitude', 'A18_Altitude_last', 'm', '1', '23_X_X_652_last');
INSERT INTO SITB_SenEst1 VALUES ('Horizontal dilusion of position', 'A19_Horizontal_dilusion_of_position_last', '0', '1', '24_X_X_659_last');
INSERT INTO SITB_SenEst1 VALUES ('5TE Battery voltage', 'A20_5TE_Battery_voltage_last', 'mV', '0', '10000_X_X_30741_last');
INSERT INTO SITB_SenEst1 VALUES ('Echo probe 10 cm', 'A21_Echo_probe_10_cm_avg', '%', '1', '10001_X_X_24067_avg');
INSERT INTO SITB_SenEst1 VALUES ('Soil temperature', 'A22_Soil_temperature_avg', '°C', '1', '10006_X_X_17665_avg');
INSERT INTO SITB_SenEst1 VALUES ('Soil temperature', 'A22_Soil_temperature_max', '°C', '1', '10006_X_X_17665_max');
INSERT INTO SITB_SenEst1 VALUES ('Soil temperature', 'A22_Soil_temperature_min', '°C', '1', '10006_X_X_17665_min');
INSERT INTO SITB_SenEst1 VALUES ('Air temperature', 'A23_Air_temperature_avg', '°C', '1', '0_X_X_0_avg');
INSERT INTO SITB_SenEst1 VALUES ('Air temperature', 'A23_Air_temperature_max', '°C', '1', '0_X_X_0_max');
INSERT INTO SITB_SenEst1 VALUES ('Air temperature', 'A23_Air_temperature_min', '°C', '1', '0_X_X_0_min');
INSERT INTO SITB_SenEst1 VALUES ('ET0', 'E3_Evapotrans', 'mm', '1', '--');
