FROM geoserver/geoserver

# Aquí puedes añadir configuraciones adicionales, instalar plugins, etc.

# Por ejemplo, si necesitas un plugin específico:
# ADD http://source/for/plugin.zip /path/within/container/
# RUN unzip /path/within/container/plugin.zip -d /path/to/geoserver/webapps/geoserver/WEB-INF/lib/
