//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE.ADCorpoica {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ADCorpoica.Wcf_AuthUsersSoap")]
    public interface Wcf_AuthUsersSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validarUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string validarUsuario(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<string> validarUsuarioAsync(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validarUsuarioRegistro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string validarUsuarioRegistro(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validarUsuarioRegistro", ReplyAction="*")]
        System.Threading.Tasks.Task<string> validarUsuarioRegistroAsync(string user, string pass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Wcf_AuthUsersSoapChannel : SE.ADCorpoica.Wcf_AuthUsersSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Wcf_AuthUsersSoapClient : System.ServiceModel.ClientBase<SE.ADCorpoica.Wcf_AuthUsersSoap>, SE.ADCorpoica.Wcf_AuthUsersSoap {
        
        public Wcf_AuthUsersSoapClient() {
        }
        
        public Wcf_AuthUsersSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Wcf_AuthUsersSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Wcf_AuthUsersSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Wcf_AuthUsersSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string validarUsuario(string user, string pass) {
            return base.Channel.validarUsuario(user, pass);
        }
        
        public System.Threading.Tasks.Task<string> validarUsuarioAsync(string user, string pass) {
            return base.Channel.validarUsuarioAsync(user, pass);
        }
        
        public string validarUsuarioRegistro(string user, string pass) {
            return base.Channel.validarUsuarioRegistro(user, pass);
        }
        
        public System.Threading.Tasks.Task<string> validarUsuarioRegistroAsync(string user, string pass) {
            return base.Channel.validarUsuarioRegistroAsync(user, pass);
        }
    }
}
