
alter table sistencial_SE1.dbo.CultivoCiclo
add CondicionId int NULL
GO

ALTER TABLE sistencial_SE1.[dbo].CultivoCiclo  WITH CHECK ADD  CONSTRAINT [FK_dbo.CultivoCiclo_dbo.Condicion_CondicionId] FOREIGN KEY([CondicionId])
REFERENCES sistencial_SE1.[dbo].Condicion ([CondicionId])
ON DELETE CASCADE
GO


update sistencial_SE1.dbo.CultivoCiclo set CondicionId = 0


SET IDENTITY_INSERT sistencial_SE1.[dbo].CultivoCiclo ON 
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(47,'Periodo de análisis 1',1,1,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(48,'Periodo de análisis 2',1,1,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(49,'Periodo de análisis 1',2,2,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(50,'Periodo de análisis 2',2,2,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(51,'Periodo de análisis 1',3,5,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(52,'Periodo de análisis 2',3,5,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(53,'Periodo de análisis 1',1,4,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(54,'Periodo de análisis 2',1,4,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(55,'Periodo de análisis 1',2,6,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(56,'Periodo de análisis 2',2,6,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(57,'Periodo de análisis 1',3,3,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(58,'Periodo de análisis 2',3,3,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(59,'Periodo de análisis 1',10,7,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(60,'Periodo de análisis 2',10,7,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(61,'Periodo de análisis 1',8,9,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(62,'Periodo de análisis 2',10,8,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(63,'Periodo de análisis 1',10,8,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(64,'Periodo de análisis 2',8,9,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(65,'Periodo de análisis 1',9,10,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(66,'Periodo de análisis 2',9,10,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(67,'Periodo de análisis 1',8,11,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(68,'Periodo de análisis 2',8,11,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(69,'Periodo de análisis 1',4,12,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(70,'Periodo de análisis 2',4,12,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(71,'Periodo de análisis 1',5,13,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(72,'Periodo de análisis 2',5,13,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(73,'Periodo de análisis 1',3,14,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(74,'Periodo de análisis 2',3,14,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(75,'Periodo de análisis 1',3,15,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(76,'Periodo de análisis 2',3,15,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(77,'Periodo de análisis 1',4,16,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(78,'Periodo de análisis 2',4,16,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(79,'Periodo de análisis 1',6,17,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(80,'Periodo de análisis 2',6,17,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(81,'Periodo de análisis 1',3,18,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(82,'Periodo de análisis 2',3,18,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(83,'Periodo de análisis 1',7,19,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(84,'Periodo de análisis 2',7,19,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(85,'Periodo de análisis 1',9,20,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(86,'Periodo de análisis 2',9,20,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(87,'Periodo de análisis 1',14,24,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(88,'Periodo de análisis 2',14,24,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(89,'Periodo de análisis 1',15,25,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(90,'Periodo de análisis 2',15,25,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(91,'Periodo de análisis 1',3,26,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(92,'Periodo de análisis 2',3,26,1)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(93,'Periodo de análisis 1',1,1,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(94,'Periodo de análisis 2',1,1,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(95,'Periodo de análisis 1',2,2,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(96,'Periodo de análisis 2',2,2,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(97,'Periodo de análisis 1',3,5,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(98,'Periodo de análisis 2',3,5,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(99,'Periodo de análisis 1',1,4,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(100,'Periodo de análisis 2',1,4,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(101,'Periodo de análisis 1',2,6,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(102,'Periodo de análisis 2',2,6,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(103,'Periodo de análisis 1',3,3,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(104,'Periodo de análisis 2',3,3,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(105,'Periodo de análisis 1',10,7,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(106,'Periodo de análisis 2',10,7,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(107,'Periodo de análisis 1',8,9,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(108,'Periodo de análisis 2',10,8,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(109,'Periodo de análisis 1',10,8,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(110,'Periodo de análisis 2',8,9,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(111,'Periodo de análisis 1',9,10,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(112,'Periodo de análisis 2',9,10,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(113,'Periodo de análisis 1',8,11,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(114,'Periodo de análisis 2',8,11,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(115,'Periodo de análisis 1',4,12,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(116,'Periodo de análisis 2',4,12,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(117,'Periodo de análisis 1',5,13,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(118,'Periodo de análisis 2',5,13,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(119,'Periodo de análisis 1',3,14,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(120,'Periodo de análisis 2',3,14,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(121,'Periodo de análisis 1',3,15,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(122,'Periodo de análisis 2',3,15,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(123,'Periodo de análisis 1',4,16,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(124,'Periodo de análisis 2',4,16,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(125,'Periodo de análisis 1',6,17,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(126,'Periodo de análisis 2',6,17,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(127,'Periodo de análisis 1',3,18,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(128,'Periodo de análisis 2',3,18,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(129,'Periodo de análisis 1',7,19,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(130,'Periodo de análisis 2',7,19,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(131,'Periodo de análisis 1',9,20,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(132,'Periodo de análisis 2',9,20,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(133,'Periodo de análisis 1',14,24,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(134,'Periodo de análisis 2',14,24,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(135,'Periodo de análisis 1',15,25,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(136,'Periodo de análisis 2',15,25,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(137,'Periodo de análisis 1',3,26,2)
INSERT INTO sistencial_SE1.[dbo].CultivoCiclo(CultivoCicloId,Nombre,CultivoId, MunicipioId,CondicionId ) VALUES(138,'Periodo de análisis 2',3,26,2)

SET IDENTITY_INSERT sistencial_SE1.[dbo].CultivoCiclo OFF


SET IDENTITY_INSERT sistencial_SE1.[dbo].CultivoTipoEtapa ON
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(55,1,10,47,1)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(56,2,11,47,2)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(57,2,12,47,3)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(58,1,11,48,1)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(59,2,12,48,2)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(60,2,1,48,3)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(61,1,10,49,2)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(62,3,11,49,3)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(63,3,11,49,4)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(64,1,11,50,2)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(65,3,12,50,3)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(66,3,12,50,4)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(67,2,5,51,5)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(68,2,6,51,6)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(69,2,7,52,5)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(70,1,9,52,6)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(71,1,10,53,1)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(72,2,11,53,2)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(73,2,12,53,3)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(74,1,11,54,1)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(75,2,12,54,2)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(76,2,1,54,3)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(77,1,10,55,2)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(78,3,11,55,3)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(79,3,11,55,4)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(80,1,11,56,2)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(81,3,12,56,3)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(82,3,12,56,4)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(83,2,5,57,5)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(84,2,6,57,6)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(85,2,7,58,5)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(86,1,9,58,6)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(87,2,5,59,1)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(88,2,7,59,2)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(89,2,9,59,3)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(90,2,5,60,1)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(91,2,7,60,2)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(92,2,9,60,3)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(93,2,1,65,1)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(94,2,6,66,2)
----
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(95,3,12,87,1)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(96,3,12,87,4)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(97,3,3,88,1)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(98,3,3,88,4)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(99,4,12,89,5)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(100,4,12,89,6)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(101,4,3,90,5)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(102,4,3,90,6)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(103,4,12,91,5)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(104,4,12,91,6)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(105,4,3,92,5)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(106,4,3,92,6)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(107,1,10,93,1)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(108,2,11,93,2)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(109,2,12,93,3)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(110,1,11,94,1)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(111,2,12,94,2)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(112,2,1,94,3)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(113,1,10,95,2)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(114,3,11,95,3)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(115,3,11,95,4)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(116,1,11,96,2)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(117,3,12,96,3)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(118,3,12,96,4)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(119,2,5,97,5)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(120,2,6,97,6)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(121,2,7,98,5)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(122,1,9,98,6)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(123,1,10,99,1)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(124,2,11,99,2)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(125,2,12,99,3)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(126,1,11,100,1)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(127,2,12,100,2)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(128,2,1,100,3)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(129,1,10,101,2)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(130,3,11,101,3)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(131,3,11,101,4)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(132,1,11,102,2)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(133,3,12,102,3)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(134,3,12,102,4)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(135,2,5,103,5)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(136,2,6,103,6)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(137,2,7,104,5)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(138,1,9,104,6)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(139,2,5,105,1)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(140,2,7,105,2)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(141,2,9,105,3)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(142,2,5,106,1)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(143,2,7,106,2)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(144,2,9,106,3)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(145,2,1,111,1)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(146,2,6,112,2)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(147,3,12,133,1)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(148,3,12,133,4)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(149,3,3,134,1)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(150,3,3,134,4)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(151,4,12,135,5)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(152,4,12,135,6)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(153,4,3,136,5)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(154,4,3,136,6)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(155,4,12,137,5)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(156,4,12,137,6)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(157,4,3,138,5)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(158,4,3,138,6)

SET IDENTITY_INSERT sistencial_SE1.[dbo].CultivoTipoEtapa OFF

--- insertando para cundinamarca utica cultivo id 7

SET IDENTITY_INSERT sistencial_SE1.dbo.CultivoEtapa ON 
insert into sistencial_SE1.dbo.CultivoEtapa(CultivoEtapaId,Nombre,Orden,Clase,RutaIcono) 
values(13,'Maduración',3,'escenario-naranja','/Content/imagenes/Etapas/EtapaCiclo2.png')
SET IDENTITY_INSERT sistencial_SE1.dbo.CultivoEtapa OFF

--actualiza ruta icono de etapa existente para que se muestre en la vista
update sistencial_SE1.dbo.CultivoEtapa set RutaIcono = '/Content/imagenes/Etapas/EtapaCiclo1.png'
where CultivoEtapaId=12

SET IDENTITY_INSERT sistencial_SE1.[dbo].CultivoTipoEtapa ON
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(159,2,6,37,12)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(160,2,7,37,13)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(161,1,8,37,4)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(162,3,9,38,12)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(163,2,11,38,13)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(164,1,12,38,4)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(165,2,6,83,12)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(166,2,7,83,13)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(167,1,8,83,4)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(168,3,9,84,12)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(169,2,11,84,13)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(170,1,12,84,4)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(171,2,6,129,12)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(172,2,7,129,13)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(173,1,8,129,4)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(174,3,9,130,12)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(175,2,11,130,13)
INSERT INTO sistencial_SE1.[dbo].CultivoTipoEtapa(CultivoTipoEtapaId,Duracion,MesInicio, CultivoCicloId,CultivoEtapaId ) VALUES(176,1,12,130,4)

SET IDENTITY_INSERT sistencial_SE1.[dbo].CultivoTipoEtapa OFF