--Selección de base de datos a utilizar
USE [sistencial_SE1]
GO

--Se eliminan las tablas existentes
DROP TABLE [dbo].[Convenciones]
GO

--Creación de la tabla de Convenciones
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Convenciones](
	[ConvencionId] [int] IDENTITY(1,1) NOT NULL,
	[NombreIndicador] [nvarchar](max) NOT NULL,
	[ValorLayer] [nvarchar](max) NULL,
	[Color] [nvarchar](max) NULL,
	[OpcionVisualizacionId] [int] NOT NULL,
 CONSTRAINT [PK_dbo.Convenciones] PRIMARY KEY CLUSTERED 
(
	[ConvencionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
ALTER TABLE dbo.Convenciones  WITH CHECK ADD
CONSTRAINT [FK_dbo.Convenciones_dbo.OpcionesVisualizacion_OpcionVisualizacionId] FOREIGN KEY([OpcionVisualizacionId])
REFERENCES dbo.OpcionesVisualizacion (OpcionVisualizacionId)
ON DELETE CASCADE
GO

--Registro de datos para la tabla de Convenciones 12/08/2015
--Subzonas (Departamento)
--Atlántico
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Directos al Mar Caribe', N'Arroyos Directos al Caribe', N'rgb(230,201,99)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Bajo Magdalena - Canal del Dique', N'Directos al Bajo Magdalena (mi)', N'rgb(189,180,151)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Directos al Bajo Magdalena', N'Bajo Magdalena - Canal del Dique  2903 (md) - 2909 (mi)', N'rgb(0,102,0)', 1)
--Norte de Santander
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Lebrija y otros directos al Magdalena', N'Río Lebrija y otros directos al Magdalena', N'rgb(74,176,96)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Quebrada El Carmen y otros', N'Quebrada El Carmen y Otros Directos al Magdalena Medio', N'rgb(179,181,147)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río del Suroeste y directos Río de Oro', N'Río del Suroeste y directos Río de Oro', N'rgb(196,10,10)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Bajo Catatumbo', N'Bajo Catatumbo', N'rgb(167,224,159)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Socuavo del Norte y Río Socuavo Sur', N'Río Socuavo del Norte y Río Socuavo Sur', N'rgb(179,124,52)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Algodonal (Alto Catatumbo)', N'Río Algodonal (Alto Catatumbo)', N'rgb(182,225,227)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Tarra', N'Río Tarra', N'rgb(255,211,127)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Zulia', N'Río Zulia', N'rgb(255,235,214)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Chítaga', N'Río Chítaga', N'rgb(198,247,218)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Pamplonita', N'Río Pamplonita', N'rgb(250,130,55)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Margua', N'Río Margua', N'rgb(106,166,129)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Alto Río Apure', N'Alto Río Apure', N'rgb(132,157,186)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Nuevo Presidente - Tres Bocas (Sardinata, Tibú)', N'Río Nuevo Presidente - Tres Bocas (Sardinata, Tibú)', N'rgb(212,155,123)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Cobugón - Río Cobaría', N'Río Cobugón - Río Cobaría', N'rgb(52,250,89)', 1)
--Huila
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Alto Magdalena', N'Alto Magdalena', N'rgb(199,126,84)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Juncal y ríos al Magdalena', N'Juncal y otros Rios dirctos al Magdalena', N'rgb(245,218,196)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Fortalecillas y otros', N'Rio Fortalecillas y otros', N'rgb(250,180,67)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Neiva', N'Rio Neiva', N'rgb(245,245,122)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Aipe, Chenche y otros', N'Río Aipe, Río Chenche y otros directos al Magdalena', N'rgb(38,115,0)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Baché', N'Río Baché', N'rgb(52,250,89)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Cabrera', N'Río Cabrera', N'rgb(149,201,179)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Páez', N'Río Páez', N'rgb(224,224,128)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Suaza', N'Río Suaza', N'rgb(107,186,104)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Timaná y otros', N'Río Timaná y otros directos al Magdalena', N'rgb(194,140,145)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Ríos Yaguará e Iquira', N'Río Yaguará y Río Iquira', N'rgb(230,65,50)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Ríos al Magdalena (mi)', N'Ríos Directos al Magdalena (mi)', N'rgb(184,64,90)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Ríos al Magdalena (md)', N'Ríos directos Magdalena (md)', N'rgb(242,138,111)', 1)
--Bolívar
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Bajo Nechí',N'Bajo Nechí', N'rgb(194,54,80)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Bajo San Jorge - La Mojana', N'Bajo San Jorge - La Mojana', N'rgb(135,43,97)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Directos Bajo Cauca', N'Directos Bajo Cauca - Cga La Raya', N'rgb(49,235,89)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Directos Bajo Magdalena', N'Directos Bajo Magdalena', N'rgb(126,166,146)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Directos Caribe Golfo de Morrosquillo', N'Directos Caribe Golfo de Morrosquillo', N'rgb(153,145,145)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Directos al Magdalena (Brazo Morales)', N'Directos al Magdalena (Brazo Morales)', N'rgb(252,232,233)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Cimitarra y otros', N'Río Cimitarra y otros directos al Magdalena', N'rgb(120,108,108)', 1)
--Cundinamarca
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Chivor', N'Chivor', N'rgb(186,207,85)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Directos al Río Meta', N'Directos al Río Meta', N'rgb(207,217,160)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Embalse del Guavio', N'Embalse del Guavio', N'rgb(179,217,124)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Bogotá', N'Río Bogotá', N'rgb(176,230,85)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Carare (Minero)', N'Río Carare (Minero)', N'rgb(214,165,109)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Guacavía', N'Río Guacavía', N'rgb(161,104,184)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Guatiquía', N'Río Guatiquía', N'rgb(224,209,110)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Guayuriba', N'Río Guayuriba', N'rgb(158,150,195)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Humea', N'Río Humea', N'rgb(209,143,119)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Negro', N'Río Negro', N'rgb(96,161,149)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Seco y otros', N'Río Seco y otros Directos al Magdalena (2123) - otros directos md (2303)', N'rgb(225,227,127)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Sumapaz', N'Río Sumapaz', N'rgb(127,212,135)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Suárez', N'Río Suárez', N'rgb(153,153,113)', 1)
--Boyacá
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Directos al Magdalena Medio', N'Directos al Magdalena Medio', N'rgb(186,207,85)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Cobugón', N'Río Cobugón', N'rgb(186,207,85)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Bojabá', N'Río Bojabá', N'rgb(186,207,85)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Chicamocha', N'Río Chicamocha', N'rgb(186,207,85)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Fonce', N'Río Fonce', N'rgb(186,207,85)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Tunjita', N'Río Tunjita', N'rgb(186,207,85)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Upía', N'Río Upía', N'rgb(186,207,85)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Cravo Sur', N'Río Cravo Sur', N'rgb(186,207,85)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Pauto', N'Río Pauto', N'rgb(186,207,85)', 1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Cusiana', N'Río Cusiana', N'rgb(186,207,85)', 1)
--Nariño
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Alto Río Putumayo',N'Alto Río Putumayo','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Chingual',N'Río Chingual','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Guáitara',N'Río Guáitara','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Iscuandé',N'Río Iscuandé','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Juananbú',N'Río Juananbú','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Mayo',N'Río Mayo','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Mira',N'Río Mira','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Patia Alto',N'Río Patia Alto','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Patia Bajo',N'Río Patia Bajo','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Patia Medio',N'Río Patia Medio','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Rosario',N'Río Rosario','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río San Juan (Frontera Ecuador)',N'Río San Juan (Frontera Ecuador)','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río San_Miguel',N'Río San_Miguel','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Tapaje',N'Río Tapaje','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Telembí',N'Río Telembí','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Tola',N'Río Tola','',1)
--Santander
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Opón',N'Río Opón','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Sogamoso',N'Río Sogamoso','',1)
--Cauca
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Purace',N'Río Purace','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Ovejas',N'Río Ovejas','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Palo',N'Río Palo','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Alto Río Cauca',N'Alto Río Cauca','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Rio Salado y otros','Rio Salado y otros directos Cauca','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Quinamayo y otros',N'Río Quinamayo y otros directos al Cauca','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Timba',N'Río Timba','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Claro, río Jamundí y otros',N'Río Claro, río Jamundí y otros directos al Cauca','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Piendamo',N'Río Piendamo','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Naya',N'Río Naya','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Desbaratado',N'Río Desbaratado','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río San Juan del Micay',N'Río San Juan del Micay','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Saija',N'Río Saija','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Timbiquí',N'Río Timbiquí','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Guapi',N'Río Guapi','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Guachicono',N'Río Guachicono','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Alto Caqueta',N'Alto Caqueta','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Ríos Cali, Lilí, Melendez y Cañaveralejo',N'Ríos Cali, río Lilí, río Melendez y río Canaveralejo','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Caqueta Medio',N'Río Caqueta Medio','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Páez',N'Río Páez','',1)
--Magdalena
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Cga Grande de Santa Marta',N'Cga Grande de Santa Marta','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Arroyo Corozal',N'Arroyo Corozal','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Directos al Bajo Magdalena',N'Directos al Bajo Magdalena (md)','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Ariguaní',N'Río Ariguaní','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Don Diego',N'Río Don Diego','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Rios Guachaca, Piedras, Manzanares',N'Rio Guachaca -Río  Piedras - Río Manzanares','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Bajo Cesar',N'Bajo Cesar','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Ancho y otros',N'Río Ancho y Otros Directos al caribe','',1)
--Córdoba
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Alto San Jorge',N'Alto San Jorge','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Bajo Sinú',N'Bajo Sinú','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Rio Canalete y otros',N'Rio Canalete y otros Arroyos Directos al Caribe','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Medio Sinú','Medio Sinú','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río San Juan',N'Río San Juan','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Alto Sinú - Urrá',N'Alto Sinú - Urrá','',1)
--Antioquia
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Alto Nechí',N'Alto Nechí','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Directos al Bajo Nechí',N'Directos al Bajo Nechí','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Directos al Cauca (md)',N'Directos al Cauca (md)','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Directos Atrato (md)',N'Directos Atrato (md)','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Directos Bajo Atrato',N'Directos Bajo Atrato','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Directos Magdalena Medio (mi)',N'Directos Magdalena Medio (mi)','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Directos Río Cauca (md)',N'Directos Río Cauca (md)','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Directos Río Cauca (mi)',N'Directos Río Cauca (mi)','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Arma',N'Río Arma','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Frío y otros',N'Río Frío y Otros Directos al Cauca','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río La Miel (Samaná)',N'Río La Miel (Samaná)','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río León',N'Río León','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Mulatos y otros',N'Río Mulatos y otros directos al Caribe','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Murindó y otros',N'Río Murindó - Directos al Atrato','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Murrí',N'Río Murrí','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Nare',N'Río Nare','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Porce',N'Río Porce','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Rió San Bartolo y otros',N'Rió San Bartolo y otros directos al Magdalena Medio','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Sucio',N'Río Sucio','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Taraza - Río Man',N'Río Taraza - Río Man','',1)
--Valle
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Fraile y otros',N'Río Fraile y otros directos al Cauca','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Ríos Guabas, Sabaletas y Sonso',N'Río Guabas, Río Sabaletas y río Sonso','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Ríos Amaime y Cerrito',N'Río Amaime y río Cerrito','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Guadalajara y otros',N'Río Guadalajara y otros directos al Cauca','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Ríos Tulua, Morales y otros',N'Ríos Tulua, río Morales y otros directos al Cauca','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Bugalagrande',N'Río Bugalagrande','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Paila',N'Río Paila','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río La Vieja',N'Río La Vieja','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Frío',N'Río Frío','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Sipí',N'Río Sipí','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Directos San Juan y Pacífico',N'Directos San Juan y Pacifico','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Calima',N'Río Calima','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Anchicayá',N'Río Anchicayá','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Timba y otros',N'Río Timba y otros directos al Pacifico','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Dagua y otros',N'Río Dagua y otros directos al Pacífico','',1)
--Tolima
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Atá',N'Río Atá','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Alto Saldaña',N'Alto Saldaña','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Cabrera',N'Río Cabrera','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Medio Saldaña',N'Medio Saldaña','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Bajo Saldaña',N'Bajo Saldaña','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Aipe, Chenche y otros',N'Río Aipe, Río Chenche y otros directos al Magdalena','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Amoyá',N'Río Amoyá','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Tetuán, Río Ortega',N'Río Tetuán, Río Ortega','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Prado',N'Río Prado','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Rïo Cucuana',N'Rïo Cucuana','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Luisa y otros',N'Río Luisa y otros directos al Magdalena','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Coello',N'Río Coello','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Opía',N'Río Opía','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Totaré',N'Río Totaré','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Lagunilla y otros',N'Río Lagunilla y Otros Directos al Magdalena','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Guarinó',N'Río Guarinó','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Directos Magdalena',N'Directos Magdalena','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Gualí',N'Río Gualí','',1)
--Guajira
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Alto Cesar',N'Alto Cesar','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Carraipia - Paraguachon',N'Río Carraipia - Paraguachon, Directos al Golfo Maracaibo','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Camarones y otros',N'Río Camarones y otros directos Caribe','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Directos Caribe',N'Directos Caribe - Ay.Sharimahana Alta Guajira','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Ranchería',N'Río Ranchería','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Tapias',N'Río Tapias','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Medio Cesar',N'Medio Cesar','',1)
--Chocó
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Alto Atrato',N'Alto Atrato','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Directos Atrato (mi)',N'Directos Atrato (mi)','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Directos frontera Panamá',N'Directos Pacifico Frontera Panamá','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Andágueda',N'Río Andágueda','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Baudó',N'Río Baudó','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Bebaramá y otros',N'Río Bebaramá y otros Directos Atrato','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Bojayá',N'Río Bojayá','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Cacarica',N'Río Cacarica','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Cajón',N'Río Cajón','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Capoma y otros','NRío Capoma y otros directos al San Juan','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Docampadó y directos Pacífico',N'Río Docampadó y Directos Pacífico','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Munguidó',N'Río Munguidó','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Napipí - Río Opogadó',N'Río Napipí - Río Opogadó','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Quito',N'Río Quito','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Salaquí  y otros',N'Río Salaquí  y otros directos Bajo Atrato','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Tamaná y otros',N'Río Tamaná y otros Directos San Juan','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Tanela y otros',N'Río Tanela y otros Directos al Caribe','',1)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Río Tolo y otros',N'Río Tolo y otros Directos al Caribe','',1)
--Estaciones (Departamento)                                                                                             
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Sinóptica principal', N'SP', N'rgb(0,255,0)', 2)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Climatológica principal', N'CP', N'rgb(255,255,0)', 2)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Climatológica ordinaria', N'CO', N'rgb(255,128,0)', 2)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Meteorológica especial', N'ME', N'rgb(255,0,0)', 2)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Pluviográfica', N'PG', N'rgb(0,0,255)', 2)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Pluviométrica', N'PM', N'rgb(130,130,130)', 2)
--Precipitación (Departamento)                                                                                          
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'<300 mm', N'< 300', N'rgb(115,0,0)', 3)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'300 - 500 mm', N'300 - 500', N'rgb(230,0,0)', 3)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'500 - 700 mm', N'500 - 700', N'rgb(137,68,68)', 3)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'<700 mm', N'< 700', N'rgb(115,0,0)', 3)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'700 - 900 mm', N'700 - 900', N'rgb(245,122,122)', 3)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'900 - 1100 mm', N'900 - 1100', N'rgb(255,190,190)', 3)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'1100 - 1300 mm', N'1100 - 1300', N'rgb(230,76,0)', 3)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'1300 - 1500 mm', N'1300 - 1500', N'rgb(230,152,0)', 3)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'1500 - 1750 mm', N'1500 - 1750', N'rgb(255,211,127)', 3)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'1750 - 2000 mm', N'1750 - 2000', N'rgb(255,255,0)', 3)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'2000 - 2250 mm', N'2000 - 2250', N'rgb(255,255,115)', 3)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'2250 - 2500 mm', N'2250 - 2500', N'rgb(209,255,115)', 3)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'2500 - 2750 mm', N'2500 - 2750', N'rgb(163,255,115)', 3)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'2750 - 3000 mm', N'2750 - 3000', N'rgb(152,230,0)', 3)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'3000 - 3500 mm', N'3000 - 3500', N'rgb(56,168,0)', 3)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'3500 - 4000 mm', N'3500 - 4000', N'rgb(0,168,132)', 3)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'4000 - 5000 mm', N'4000 - 5000', N'rgb(115,178,255)', 3)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'5000 - 6000 mm', N'5000 - 6000', N'rgb(0,92,230)', 3)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'6000 - 7000 mm', N'6000 - 7000', N'rgb(0,38,115)', 3)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'7000 - 8000 mm', N'7000 - 8000', N'rgb(0,38,115)', 3)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'8000 - 9000 mm', N'8000 - 9000', N'rgb(169,0,230)', 3)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'7000 - 9000 mm', N'7000 - 9000', N'rgb(169,0,230)', 3)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'9000 - 11000 mm', N'9000 - 11000', N'rgb(112,68,137)', 3)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'>11000 mm', N'> 11000', N'rgb(76,0,115)', 3)

--Conglomerados (Departamento)                                                                                          
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'1', N'1', N'rgb(79,129,189)', 4)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'2', N'2', N'rgb(230,0,0)', 4)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'3', N'3', N'rgb(76,230,0)', 4)
--Temperatura mínima multianual (Departamento)                                                                          
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'< 0 °C', N'< 0', N'rgb(104,104,104)', 5)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'0 - 2 °C', N'0 - 2', N'rgb(132,0,168)', 5)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'2 - 4 °C', N'2 - 4', N'rgb(170,102,205)', 5)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'4 - 6 °C', N'4 - 6', N'rgb(0,77,168)', 5)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'6 - 8 °C', N'6 - 8', N'rgb(0,112,255)', 5)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'8 - 10 °C', N'8 - 10', N'rgb(0,169,230)', 5)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'10 - 12 °C', N'10 - 12', N'rgb(115,223,255)', 5)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'12 - 14 °C', N'12 - 14', N'rgb(0,230,169)', 5)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'14 - 16 °C', N'14 - 16', N'rgb(122,245,202)', 5)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'16 - 18 °C', N'16 - 18', N'rgb(85,255,0)', 5)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'18 - 20 °C', N'18 - 20', N'rgb(209,255,115)', 5)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'20 - 22 °C', N'20 - 22', N'rgb(255,255,0)', 5)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'22 - 24 ºC', N'22 - 24', N'rgb(255,170,0)', 5)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'24 - 26 ºC', N'24 - 26', N'rgb(255,170,0)', 5)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'> 24 ºC', N'> 24', N'rgb(255,0,0)', 5)
--Temperatura media multianual (Departamento)                                                                           
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES ( N'< 6 ºC', N'< 6', N'rgb(104,104,104)', 6)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES ( N'6 - 8 ºC', N'6 - 8', N'rgb(0,77,168)', 6)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES ( N'8 - 10 ºC', N'8 - 10', N'rgb(0,169,230)', 6)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES ( N'10 - 12 ºC', N'10 - 12', N'rgb(115,223,255)', 6)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES ( N'12 - 14 ºC', N'12 - 14', N'rgb(0,230,169)', 6)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES ( N'16 - 18 ºC', N'16 - 18', N'rgb(56,168,0)', 6)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES ( N'18 - 20 ºC', N'18 - 20', N'rgb(76,230,0)', 6)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES ( N'20 - 22 ºC', N'20 - 22', N'rgb(170,255,0)', 6)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES ( N'22 - 24 ºC', N'22 - 24', N'rgb(255,255,115)', 6)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES ( N'24 - 26 ºC', N'24 - 26', N'rgb(255,255,0)', 6)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES ( N'26 - 28 ºC', N'26 - 28', N'rgb(255,170,0)', 6)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES ( N'28 - 30 ºC', N'28 - 30', N'rgb(205,102,102)', 6)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES ( N'> 30 ºC', N'> 30', N'rgb(230,0,0)', 6)
--Temperatura máxima multianual (Departamento)                                                                          
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'0 - 8 ºC', N'0 - 8', N'rgb(255,127,127)', 7)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'< 8 ºC', N'< 8', N'rgb(255,127,127)', 7)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'8 - 10 ºC', N'8 - 10', N'rgb(255,127,127)', 7)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'10 - 12 ºC', N'10 - 12', N'rgb(255,127,127)', 7)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'12 - 14 ºC', N'12 - 14', N'rgb(255,127,127)', 7)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'14 - 16 ºC', N'14 - 16', N'rgb(255,127,127)', 7)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'16 - 18 ºC', N'16 - 18', N'rgb(255,127,127)', 7)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'18 - 20 ºC', N'18 - 20', N'rgb(255,127,127)', 7)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'20 - 22 ºC', N'20 - 22', N'rgb(255,127,127)', 7)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'22 - 24 ºC', N'22 - 24', N'rgb(255,127,127)', 7)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'24 - 26 ºC', N'24 - 26', N'rgb(255,127,127)', 7)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'26 - 28 ºC', N'26 - 28', N'rgb(255,127,127)', 7)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'28 - 30 ºC', N'28 - 30', N'rgb(255,127,127)', 7)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'30 - 32 ºC', N'30 - 32', N'rgb(255,127,127)', 7)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'32 - 34 ºC', N'32 - 34', N'rgb(230,0,0)', 7)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'> 34 ºC', N'> 34', N'rgb(115,0,0)', 7)
--Brillo solar (Departamento)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'< 1100 horas', N'<1100', N'rgb(60,73,77)', 8)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'1100 - 1300 horas', N'1100 - 1300', N'rgb(107,153,145)', 8)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'1300 - 1500 horas', N'1300 - 1500', N'rgb(89,179,149)', 8)                                                                                      
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'1500 - 1700 horas', N'1500 - 1700', N'rgb(85,255,0)', 8)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'1700 - 1900 horas', N'1700 - 1900', N'rgb(172,230,115)', 8)                                                                                      
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'1900 - 2100 horas', N'1900 - 2100', N'rgb(217,255,102)', 8)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'2100 - 2300 horas', N'2100 - 2300', N'rgb(255,255,0)', 8)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'2300 - 2500 horas', N'2300 - 2500', N'rgb(255,128,0)', 8)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'> 2300 horas', N'> 2300', N'rgb(255,128,0)', 8)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'2500 - 2700 horas', N'2500 - 2700', N'rgb(230,76,0)', 8)
--Evapotranspiración (Departamento)                                                                                     
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'800 - 1000 mm', N'800 - 1000', N'rgb(179,214,156)', 9)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'1000 - 1200 mm', N'1000 - 1200', N'rgb(255,255,0)', 9)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'1200 - 1400 mm', N'1200 - 1400', N'rgb(179,214,156)', 9)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'1400 - 1600 mm', N'1400 - 1600', N'rgb(255,255,0)', 9)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'1600 - 1800 mm', N'1600 - 1800', N'rgb(255,170,0)', 9)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'1800 - 2000 mm', N'1800 - 2000', N'rgb(179,214,156)', 9)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'2000 - 2200 mm', N'2000 - 2200', N'rgb(255,255,0)', 9)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'> 2200 mm', N'> 2200', N'rgb(255,170,0)', 9)
--Humedad relativa (Departamento)                                                                                       
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'< 65%', N'<65%', N'', 10)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'65% - 70%', N'65% - 70%', N'', 10)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'70% - 75%', N'70% - 75%', N'', 10)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'75% - 80%', N'75% - 80%', N'rgb(208,255,115)', 10)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'80% - 85%', N'80% - 85%', N'rgb(85,255,0)', 10)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'85% - 90%', N'85% - 90%', N'rgb(85,255,0)', 10)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'90% - 95%', N'90% - 95%', N'rgb(85,255,0)', 10)
--Anomalía precipitación El Niño (Departamento)                                                                         
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'< -100%', N'<-100%', N'rgb(115,0,0)', 11)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'-100% - -80%', N'-100% - -80%', N'rgb(230,0,0)', 11)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'-80% - -60%', N'-80% - -60%', N'rgb(230,76,0)', 11)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'-60% - -40%', N'-60% - -40%', N'rgb(255,170,0)', 11)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'-40% - -20%', N'-40% - -20%', N'rgb(255,211,127)', 11)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'-20% - 0%', N'-20% - 0%', N'rgb(255,235,175)', 11)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'> 0%', N'>0%', N'rgb(204,204,204)', 11)
--Anomalía precipitación La Niña (Departamento)                                                                         
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'< 0%', N'<0%', N'rgb(204,204,204)', 12)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'0% - 20%', N'0% - 20%', N'rgb(190,255,232)', 12)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'20% - 40%', N'20% - 40%', N'rgb(115,255,223)', 12)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'40% - 60%', N'40% - 60%', N' rgb(0,197,255)', 12)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'60% - 80%', N'60% - 80%', N'rgb(0,132,168)', 12)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'80% - 100%', N'80% - 100%', N'rgb(0,76,168)', 12)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'> 100%', N'>100%', N'rgb(0,38,115)', 12)
--Anomalía temperatura mínima La Niña (Departamento)          
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'-2 °C a -1,5 °C', N'-2,0 - -1,5', N'rgb(0,230,168)', 13)                                                          
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'-1,5 °C a -1 °C', N'-1,5 - -1,0', N'rgb(0,230,168)', 13)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'-1 °C a -0,5 °C', N'-1,0 - -0,5', N'rgb(0,230,168)', 13)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'-0,5 °C a -0,25 °C', N'-0,5 - -0,25', N'rgb(115,255,222)', 13)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'-0,25 °C a 0 °C', N'-0,25 - 0', N'rgb(191,255,233)', 13)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'0 °C a 0,25°C', N'0 - 0,25', N'rgb(234,255,191)', 13)
--Anomalía temperatura máxima La Niña (Departamento)      
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'-2 °C a -1,5 °C', N'-2,0 - -1,5', N'rgb(0,230,168)', 14)                                                          
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'-1,5 °C a -1 °C', N'-1,5 - -1,0', N'rgb(0,230,168)', 14)                                                              
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'-1 °C a -0,5 °C', N'-1,0 - -0,5', N'rgb(0,230,168)', 14)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'-0,5 °C a -0,25 °C', N'-0,5 - -0,25', N'rgb(115,255,222)', 14)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'-0,25 °C a 0 °C', N'-0,25 - 0', N'rgb(191,255,233)', 14)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'0 °C a 0,25°C', N'0 - 0,25', N'rgb(234,255,191)', 14)
--Anomalía temperatura mínima El Niño (Departamento)                                                                    
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'0 °C a 0,25°C', N'0 - 0,25', N'rgb(234,255,191)', 15)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'0,25 °C a 0,5°C', N'0,25 - 0,5', N'rgb(255,235,176)', 15)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'0,5 °C a 1 °C', N'0,5 - 1,0', N'rgb(255,210,128)', 15)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'1 °C a 1,5 °C', N'1,0 - 1,5', N'rgb(255,168,128)', 15)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'1 °C a 1,5 °C', N'1,0 -1,5', N'rgb(255,168,128)', 15)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'1,5 °C a 2 °C', N'1,5 - 2', N'rgb(255,168,128)', 15)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'2 °C a 3 °C', N'1,5 - 2', N'rgb(255,168,128)', 15)
--Anomalía temperatura máxima El Niño (Departamento)                                                                    
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'0 °C a 0,25°C', N'0 - 0,25', N'rgb(234,255,191)', 16)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'0,25 °C a 0,5°C', N'0,25 - 0,5', N'rgb(255,235,176)', 16)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'0,5 °C a 1 °C', N'0,5 - 1,0', N'rgb(255,210,128)', 16)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'1 °C a 1,5 °C', N'1,0 - 1,5', N'rgb(255,168,128)', 16)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'1,5 °C a 2 °C', N'1,5 - 2', N'rgb(255,168,128)', 16)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'2 °C a 3 °C', N'1,5 - 2', N'rgb(255,168,128)', 16)
--Frecuencia exceso (Departamento)                                                                                      
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Muy baja', N'Muy baja', N'rgb(0,97,0)', 17)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Baja', N'Baja', N'rgb(122,171,0)', 17)                                                                                   
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Media', N'Media', N'rgb(255,255,0)', 17)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Alta', N'Alta', N'rgb(255,153,0)', 17)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Muy alta', N'Muy alta', N'rgb(255,34,0)', 17)
--Frecuencia déficit (Departamento)  
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Muy baja', N'Muy baja', N'rgb(0,97,0)', 18)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Baja', N'Baja', N'rgb(122,171,0)', 18)                                                                                   
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Media', N'Media', N'rgb(255,255,0)', 18)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Alta', N'Alta', N'rgb(255,153,0)', 18)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Muy alta', N'Muy alta', N'rgb(255,34,0)', 18)
--Susceptibilidad inundación (Departamento)   
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Sin información', N'Sin información', N'', 19)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Isla', N'Isla', N'', 19)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Alta', N'Alta', N'rgb(230,0,0)', 19)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Media', N'Media', N'rgb(255,255,0)', 19)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Baja', N'Baja', N'rgb(112,168,0)', 19)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Marina', N'Marina', N'rgb(0,230,169)', 19)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Cuerpo de agua', N'Cuerpo de Agua', N'rgb(0,92,230)', 19)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Cuerpo de agua', N'Cuerpo de agua', N'rgb(0,92,230)', 19)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'No susceptible', N'No', N'rgb(240,240,240)', 19)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'No susceptible', N'No susceptible', N'rgb(240,240,240)', 19)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Urbano', N'Urbano', N'rgb(104,104,104)', 19)
--Susceptibilidad inundación 2010-2011 (Departamento)                                                                   
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Cuerpos de agua', N'Cuerpos de agua', N'rgb(0,92,230)', 20)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Inundación 2010 - 2011', N'Inundación 2010 - 2011', N'rgb(255,0,0)', 20)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Inundación', N'Inundación', N'', 20)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Inundables periódicamente', N'Zonas inundables periódicamente', N'rgb(190,232,255)', 20)               
--NDVI (Municipio)                                                                                                         
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Estable', N'Estable', N'rgba(114,176,68,1)', 21)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Muy leve', N'Muy leve', N'rgba(205,245,122,1)', 21)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Leve', N'Leve', N'rgba(255,255,0,1)', 21)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Moderado', N'Moderado', N'rgba(230,152,0,1)', 21)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Severo', N'Severo', N'rgba(255,0,0,1)', 21)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Sin dato', N'Sin dato', '', 21)

INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Cuerpos de agua', N'cuerpoagua1', N'rgba(0,0,255,1)', 22)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Cuerpos de agua', N'cuerpoagua2', N'rgba(0,0,255,1)', 23)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Normal', N'normal', N'green', 24)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Húmedo', N'humedo', N'blue', 24)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Seco', N'seco', N'red', 24)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Por encima (>40%)', N'encima', N'blue', 25)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Dentro', N'dentro', N'green', 25)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Por debajo (>40%)', N'debajo', N'red', 25)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Nicho productivo óptimo o con leves restricciones ', N'1', N'rgba(0,97,0,1)', 26)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Áreas con suelos óptimos o con leves restricciones y alta exposición a déficit hídrico ', N'2', N'rgba(255,255,115,1)', 26)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Áreas con suelos óptimos o con leves restricciones y alta exposición a exceso hídrico ', N'3', N'rgba(255,255,115,1)', 26)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Nicho productivo condicionado a prácticas de manejo y/o conservación ', N'4', N'rgba(209,255,115,1)', 26)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Áreas condicionadas a prácticas de manejo y/o conservación y alta exposición a déficit hídrico ', N'5', N'rgba(255,170,0,1)', 26)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Áreas condicionadas a prácticas de manejo y/o conservación y alta exposición a exceso hídrico', N'6', N'rgba(255,170,0,1)', 26)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Áreas con suelos no aptos ', N'7', N'rgba(230,0,0,1)', 26)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Áreas con suelos no aptos y alta exposición a déficit hídrico ', N'8', N'rgba(230,0,0,1)', 26)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Áreas con suelos no aptos y alta exposición a exceso hídrico ', N'9', N' rgba(230,0,0,1)', 26)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Nicho productivo óptimo o con leves restricciones ', N'1', N'rgba(0,97,0,1)', 27)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Áreas con suelos óptimos o con leves restricciones y alta exposición a déficit hídrico ', N'2', N'rgba(255,255,115,1)', 27)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Áreas con suelos óptimos o con leves restricciones y alta exposición a exceso hídrico ', N'3', N'rgba(255,255,115,1)', 27)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Nicho productivo condicionado a prácticas de manejo y/o conservación ', N'4', N'rgba(209,255,115,1)', 27)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Áreas condicionadas a prácticas de manejo y/o conservación y alta exposición a déficit hídrico ', N'5', N'rgba(255,170,0,1)', 27)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Áreas condicionadas a prácticas de manejo y/o conservación y alta exposición a exceso hídrico', N'6', N'rgba(255,170,0,1)', 27)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Áreas con suelos no aptos ', N'7', N'rgba(230,0,0,1)', 27)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Áreas con suelos no aptos y alta exposición a déficit hídrico ', N'8', N'rgba(230,0,0,1)', 27)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Áreas con suelos no aptos y alta exposición a exceso hídrico ', N'9', N' rgba(230,0,0,1)', 27)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Nicho productivo óptimo o con leves restricciones ', N'1', N'rgba(0,97,0,1)', 28)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Áreas con suelos óptimos o con leves restricciones y alta exposición a déficit hídrico ', N'2', N'rgba(255,255,115,1)', 28)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Áreas con suelos óptimos o con leves restricciones y alta exposición a exceso hídrico ', N'3', N'rgba(255,255,115,1)', 28)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Nicho productivo condicionado a prácticas de manejo y/o conservación ', N'4', N'rgba(209,255,115,1)', 28)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Áreas condicionadas a prácticas de manejo y/o conservación y alta exposición a déficit hídrico ', N'5', N'rgba(255,170,0,1)', 28)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Áreas condicionadas a prácticas de manejo y/o conservación y alta exposición a exceso hídrico', N'6', N'rgba(255,170,0,1)', 28)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Áreas con suelos no aptos ', N'7', N'rgba(230,0,0,1)', 28)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Áreas con suelos no aptos y alta exposición a déficit hídrico ', N'8', N'rgba(230,0,0,1)', 28)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Áreas con suelos no aptos y alta exposición a exceso hídrico ', N'9', N' rgba(230,0,0,1)', 28)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'green', 29)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'yellow', 30)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'yellow', 31)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'red', 31)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo vacio', N'', N'', 32)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'red', 32)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo vacio', N'', N'', 33)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'red', 33)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'green', 34)
GO                                                                                                                      
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'yellow', 35)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'yellow', 36)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'red', 36)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo vacio', N'', N'', 37)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'red', 37)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo vacio', N'', N'', 38)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'red', 38)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'yellow', 39)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'red', 39)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo vacio', N'', N'', 40)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'red', 40)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'green', 41)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'yellow', 42)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'yellow', 43)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'red', 43)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo vacio', N'', N'', 44)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'red', 44)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo vacio', N'', N'', 45)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'red', 45)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'green', 46)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'yellow', 47)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'yellow', 48)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'red', 48)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo vacio', N'', N'', 49)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'red', 49)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo vacio', N'', N'', 50)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'red', 50)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'yellow', 51)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'red', 51)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo vacio', N'', N'', 52)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'red', 52)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'green', 53)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'yellow', 54)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'yellow', 55)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'red', 55)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo vacio', N'', N'', 56)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'red', 56)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo vacio', N'', N'', 57)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'red', 57)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'green', 58)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'yellow', 59)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'yellow', 60)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'red', 60)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo vacio', N'', N'', 61)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'red', 61)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo vacio', N'', N'', 62)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'red', 62)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'yellow', 63)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'red', 63)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo vacio', N'', N'', 64)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'circulo', N'', N'red', 64)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Nicho productivo condicionado a prácticas de manejo y/o conservación ', N'4', N'rgba(209,255,115,1)', 26)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Áreas con suelos no aptos ', N'7', N'rgba(230,0,0,1)', 26)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Nicho productivo condicionado a prácticas de manejo y/o conservación ', N'4', N'rgba(209,255,115,1)', 28)
INSERT [dbo].[Convenciones] ([NombreIndicador], [ValorLayer], [Color], [OpcionVisualizacionId]) VALUES (N'Áreas con suelos no aptos ', N'7', N'rgba(230,0,0,1)', 28)

GO
